---
# Re-write of: 
# https://github.com/network-automation/toolkit/blob/master/playbooks/network_report.yml
# https://github.com/network-automation/toolkit/blob/master/roles/build_report/tasks/main.yml

- name: Collect facts
  hosts: routers
  gather_facts: true

  tasks:
    - name: Debug message
      ansible.builtin.debug:
        msg: "OK"

- hosts: "{{ HOSTS }}"
  become: yes
  vars:
    report_server: node1
  
  tasks:
    - name: HOSTVARS
      ansible.builtin.debug: 
        msg: "{{ hostvars }}"

    - name: GROUPS
      ansible.builtin.debug: 
        msg: "{{ groups }}"

    - ansible.builtin.include_role:
        name: demo.patching.build_report_network

    - block:
      - name: install apache
        ansible.builtin.yum:
          name: httpd
          state: present
        check_mode: no

      - ansible.builtin.file:
          path: /var/www/html/reports/
          state: directory
        check_mode: no

      - ansible.builtin.copy:
          dest: /var/www/html/reports/.htaccess
          content: Options +Indexes
        check_mode: no

      - name: start httpd
        ansible.builtin.service:
          name: httpd
          state: started
        check_mode: no

      delegate_to: "{{ report_server }}"
      run_once: yes