---
- hosts: localhost
  gather_facts: no
  vars_files: setup.yml

  tasks:
  - name: Setup CV
    include_role:
      name: redhat.satellite.content_views

  - name: Publish CV
    include_role:
      name: redhat.satellite.content_view_publish
    vars:
      satellite_content_views:
      - RHEL7
      - RHEL8

  - name: Setup Lifecycle Environment
    include_role:
      name: redhat.satellite.lifecycle_environments

  - name: redhat.satellite.content_view_publish CV
    redhat.satellite.content_view_version:
      organization: "{{ satellite_organization }}"
      content_view: "{{ item }}"
      lifecycle_environments:
        - "{{ item }}_Dev"
        - "{{ item }}_QA"
        - "{{ item }}_Prod"
    loop:
      - RHEL7
      - RHEL8

  - name: Setup activation_keys
    include_role:
      name: redhat.satellite.activation_keys

  - name: Add SCAP Tailoring File
    redhat.satellite.scap_tailoring_file:
      name: RHEL7_STIG
      organizations: "{{ satellite_organization }}"
      scap_file: files/ssg-rhel7-ds-tailoring.xml
