---
- hosts: "{{ HOSTS }}"
  become: true
  vars:
    compliance_profile: undef

  tasks:
    - name: Check OS Type
      assert:
        that: "ansible_os_family == 'RedHat'"

    - name: Run Compliance Profile
      include_role:
        name: "dmeo.compliance.rhel{{ ansible_distribution_major_version }}STIG"
